# Generated by Django 5.0.3 on 2024-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_extra_tag',
            field=models.CharField(choices=[(None, 'Unknown'), ('Fancy Product', 'Fancy Product'), ('Sale', 'Sale'), ('Special Item', 'Special Item'), ('Bestseller', 'Bestseller'), ('In Stock', 'In Stock'), ('Not In Stock', 'Not In Stock')], default='Unknown', verbose_name='item extra tag'),
        ),
    ]
