# Generated by Django 5.0.3 on 2024-06-14 08:25
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_item_item_extra_tag'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
