# Generated by Django 5.0.3 on 2024-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_item_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description_en',
            field=models.TextField(blank=True, db_index=True, verbose_name='item description in English'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description_ru',
            field=models.TextField(blank=True, db_index=True, verbose_name='item description in Russian'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description_zh_hans',
            field=models.TextField(blank=True, db_index=True, verbose_name='item description in Chinese'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name_en',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='item name in English'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name_ru',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='item name in Russian'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name_zh_hans',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='item name in Chinese'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5, verbose_name='item price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price_extra_new',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='extra new item price'),
        ),
    ]
