# Generated by Django 5.0.3 on 2024-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_item_item_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(db_index=True, max_length=50, verbose_name='category name in English'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(db_index=True, max_length=50, verbose_name='category name in Russian'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_zh_hans',
            field=models.CharField(db_index=True, max_length=50, verbose_name='category name in Chinese'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_number',
            field=models.IntegerField(auto_created=True, db_index=True, unique=True, verbose_name='category number'),
        ),
    ]
